/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraliga;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lukep
 */
public class CopaDeEspaña extends javax.swing.JFrame {

    /**
     * Creates new form CopaDeEspaña
     */
    public CopaDeEspaña() {
        initComponents();
    }
    
    public CopaDeEspaña(String cf1, String cf2, String cf3, String cf4, String cf5, String cf6, String cf7, String cf8 ){
        initComponents();
        cuartofinalista1.setText(cf1);
        cuartofinalista2.setText(cf2);
        cuartofinalista3.setText(cf3);
        cuartofinalista4.setText(cf4);
        cuartofinalista5.setText(cf5);
        cuartofinalista6.setText(cf6);
        cuartofinalista7.setText(cf7);
        cuartofinalista8.setText(cf8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuartofinalista2 = new javax.swing.JButton();
        tcuartofinalista2 = new javax.swing.JTextField();
        tcuartofinalista1 = new javax.swing.JTextField();
        cuartofinalista1 = new javax.swing.JButton();
        cuartosfinal1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cuartofinalista4 = new javax.swing.JButton();
        tcuartofinalista4 = new javax.swing.JTextField();
        tcuartofinalista3 = new javax.swing.JTextField();
        cuartofinalista3 = new javax.swing.JButton();
        cuartosfinal2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cuartofinalista8 = new javax.swing.JButton();
        tcuartofinalista8 = new javax.swing.JTextField();
        tcuartofinalista7 = new javax.swing.JTextField();
        cuartofinalista7 = new javax.swing.JButton();
        cuartosfinal4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cuartofinalista6 = new javax.swing.JButton();
        tcuartofinalista6 = new javax.swing.JTextField();
        tcuartofinalista5 = new javax.swing.JTextField();
        cuartofinalista5 = new javax.swing.JButton();
        cuartosfinal3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        semifinalista2 = new javax.swing.JButton();
        tsemifinalista2 = new javax.swing.JTextField();
        tsemifinalista1 = new javax.swing.JTextField();
        semifinalista1 = new javax.swing.JButton();
        semifinal1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        semifinal2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        semifinalista4 = new javax.swing.JButton();
        tsemifinalista4 = new javax.swing.JTextField();
        tsemifinalista3 = new javax.swing.JTextField();
        semifinalista3 = new javax.swing.JButton();
        final1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        finalista2 = new javax.swing.JButton();
        tfinalista2 = new javax.swing.JTextField();
        tfinalista1 = new javax.swing.JTextField();
        finalista1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        winner = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        cuartofinalista2.setText("PALMA FUTSAL");

        cuartofinalista1.setText("EL POZO MURCIA");

        cuartosfinal1.setText("CALCULAR");
        cuartosfinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartosfinal1ActionPerformed(evt);
            }
        });

        jLabel1.setText("CUARTOS DE FINAL");

        cuartofinalista4.setText("OSASUNA MAGNA");

        cuartofinalista3.setText("FC BARCELONA");

        cuartosfinal2.setText("CALCULAR");
        cuartosfinal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartosfinal2ActionPerformed(evt);
            }
        });

        jLabel2.setText("CUARTOS DE FINAL");

        cuartofinalista8.setText("JIMBEE CARTAGENA");

        cuartofinalista7.setText("JAEN FS");

        cuartosfinal4.setText("CALCULAR");
        cuartosfinal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartosfinal4ActionPerformed(evt);
            }
        });

        jLabel3.setText("CUARTOS DE FINAL");

        cuartofinalista6.setText("LEVANTE UD");

        cuartofinalista5.setText("MOVISTAR INTER");

        cuartosfinal3.setText("CALCULAR");
        cuartosfinal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartosfinal3ActionPerformed(evt);
            }
        });

        jLabel4.setText("CUARTOS DE FINAL");

        semifinal1.setText("CALCULAR");
        semifinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semifinal1ActionPerformed(evt);
            }
        });

        jLabel5.setText("SEMIFINAL");

        semifinal2.setText("CALCULAR");
        semifinal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semifinal2ActionPerformed(evt);
            }
        });

        jLabel6.setText("SEMIFINAL");

        final1.setText("CALCULAR");
        final1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                final1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("FINAL");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("WINNER: ");

        winner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("COPA DE ESPAÑA ");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tcuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tcuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cuartosfinal2)
                                .addGap(10, 10, 10)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(173, 173, 173)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tcuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tcuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cuartosfinal1)
                                    .addGap(10, 10, 10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(173, 173, 173)))
                        .addGap(154, 154, 154)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tcuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tcuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cuartosfinal3)
                            .addGap(10, 10, 10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tcuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tcuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cuartosfinal4)
                            .addGap(10, 10, 10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(173, 173, 173)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(semifinal1)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(semifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tsemifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tsemifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(semifinal2)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(semifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tsemifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tsemifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(final1)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)))
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(winner, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tcuartofinalista2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(tcuartofinalista1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(cuartofinalista1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cuartofinalista2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(cuartosfinal1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tcuartofinalista6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(tcuartofinalista5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(cuartofinalista5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cuartofinalista6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(cuartosfinal3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tsemifinalista2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(tsemifinalista1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(semifinalista1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(semifinalista2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(semifinal1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tsemifinalista4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(tsemifinalista3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(semifinalista3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(semifinalista4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(semifinal2)))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(winner)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfinalista2)
                                .addComponent(tfinalista1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(finalista1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(final1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tcuartofinalista4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(tcuartofinalista3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(cuartofinalista3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cuartofinalista4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(cuartosfinal2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tcuartofinalista8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(tcuartofinalista7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(cuartofinalista7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cuartofinalista8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(cuartosfinal4)))
                        .addGap(89, 89, 89))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuartosfinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartosfinal1ActionPerformed
        try {
            int num1 = Integer.parseInt(tcuartofinalista1.getText());
            int num2 = Integer.parseInt(tcuartofinalista2.getText());
            if(num1 > num2){
                semifinalista1.setText(cuartofinalista1.getText());
            }else if(num2 > num1){
                semifinalista1.setText(cuartofinalista2.getText());
            }
        }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(this, "Formato invalido");

        }
    }//GEN-LAST:event_cuartosfinal1ActionPerformed

    private void cuartosfinal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartosfinal4ActionPerformed
        // TODO add your handling code here:
          try {
            int num1 = Integer.parseInt(tcuartofinalista7.getText());
            int num2 = Integer.parseInt(tcuartofinalista8.getText());
            if(num1 > num2){
                semifinalista4.setText(cuartofinalista7.getText());
            }else if(num2 > num1){
                semifinalista4.setText(cuartofinalista8.getText());
            }
        }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(this, "Formato invalido");

        }
    }//GEN-LAST:event_cuartosfinal4ActionPerformed

    private void cuartosfinal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartosfinal3ActionPerformed

            try {
               int num1 = Integer.parseInt(tcuartofinalista5.getText());
               int num2 = Integer.parseInt(tcuartofinalista6.getText());
               if(num1 > num2){
                   semifinalista3.setText(cuartofinalista5.getText());
               }else if(num2 > num1){
                   semifinalista3.setText(cuartofinalista6.getText());
               }
           }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Formato invalido");

           }
        
    }//GEN-LAST:event_cuartosfinal3ActionPerformed

    private void semifinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semifinal1ActionPerformed
        // TODO add your handling code here:
        if("".equals(semifinalista1.getText()) || semifinalista2.getText() == ""){
            JOptionPane.showMessageDialog(this, "Falta un partido por disputarse");
            tsemifinalista1.setText("");
            tsemifinalista2.setText("");
        }else{
            try {
               int num1 = Integer.parseInt(tsemifinalista1.getText());
               int num2 = Integer.parseInt(tsemifinalista2.getText());
               if(num1 > num2){
                   finalista1.setText(semifinalista1.getText());
               }else if(num2 > num1){
                   finalista1.setText(semifinalista2.getText());
               }
           }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Formato invalido");

           }    
        }
    }//GEN-LAST:event_semifinal1ActionPerformed

    private void semifinal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semifinal2ActionPerformed
        // TODO add your handling code here:
         if("".equals(semifinalista3.getText()) || semifinalista4.getText() == ""){
            JOptionPane.showMessageDialog(this, "Falta un partido por disputarse");
            tsemifinalista3.setText("");
            tsemifinalista4.setText("");
        }else{
            try {
               int num1 = Integer.parseInt(tsemifinalista3.getText());
               int num2 = Integer.parseInt(tsemifinalista4.getText());
               if(num1 > num2){
                   finalista2.setText(semifinalista3.getText());
               }else if(num2 > num1){
                   finalista2.setText(semifinalista4.getText());
               }
           }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Formato invalido");

           } 
        }
    }//GEN-LAST:event_semifinal2ActionPerformed

    private void cuartosfinal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartosfinal2ActionPerformed
        // TODO add your handling code here:
          try {
            int num1 = Integer.parseInt(tcuartofinalista3.getText());
            int num2 = Integer.parseInt(tcuartofinalista4.getText());
            if(num1 > num2){
                semifinalista2.setText(cuartofinalista3.getText());
            }else if(num2 > num1){
                semifinalista2.setText(cuartofinalista4.getText());
            }
        }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(this, "Formato invalido");

        }
    }//GEN-LAST:event_cuartosfinal2ActionPerformed

    private void final1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_final1ActionPerformed
        // TODO add your handling code here:
        if("".equals(finalista1.getText()) || finalista2.getText() == ""){
            JOptionPane.showMessageDialog(this, "Falta un partido por disputarse");
            tfinalista1.setText("");
            tfinalista2.setText("");
        }else{
            try {
               int num1 = Integer.parseInt(tfinalista1.getText());
               int num2 = Integer.parseInt(tfinalista2.getText());
               if(num1 > num2){
                   winner.setText(finalista1.getText());
               }else if(num2 > num1){
                   winner.setText(finalista2.getText());
               }
           }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Formato invalido");

           }    
        }
    }//GEN-LAST:event_final1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CopaDeEspaña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CopaDeEspaña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CopaDeEspaña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CopaDeEspaña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CopaDeEspaña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cuartofinalista1;
    private javax.swing.JButton cuartofinalista2;
    private javax.swing.JButton cuartofinalista3;
    private javax.swing.JButton cuartofinalista4;
    private javax.swing.JButton cuartofinalista5;
    private javax.swing.JButton cuartofinalista6;
    private javax.swing.JButton cuartofinalista7;
    private javax.swing.JButton cuartofinalista8;
    private javax.swing.JButton cuartosfinal1;
    private javax.swing.JButton cuartosfinal2;
    private javax.swing.JButton cuartosfinal3;
    private javax.swing.JButton cuartosfinal4;
    private javax.swing.JButton final1;
    private javax.swing.JButton finalista1;
    private javax.swing.JButton finalista2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton semifinal1;
    private javax.swing.JButton semifinal2;
    private javax.swing.JButton semifinalista1;
    private javax.swing.JButton semifinalista2;
    private javax.swing.JButton semifinalista3;
    private javax.swing.JButton semifinalista4;
    private javax.swing.JTextField tcuartofinalista1;
    private javax.swing.JTextField tcuartofinalista2;
    private javax.swing.JTextField tcuartofinalista3;
    private javax.swing.JTextField tcuartofinalista4;
    private javax.swing.JTextField tcuartofinalista5;
    private javax.swing.JTextField tcuartofinalista6;
    private javax.swing.JTextField tcuartofinalista7;
    private javax.swing.JTextField tcuartofinalista8;
    private javax.swing.JTextField tfinalista1;
    private javax.swing.JTextField tfinalista2;
    private javax.swing.JTextField tsemifinalista1;
    private javax.swing.JTextField tsemifinalista2;
    private javax.swing.JTextField tsemifinalista3;
    private javax.swing.JTextField tsemifinalista4;
    private javax.swing.JTextField winner;
    // End of variables declaration//GEN-END:variables
}
