/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraliga;

import javax.swing.JOptionPane;

/**
 *
 * @author lukep
 */
public class PlayOffTitulo extends javax.swing.JFrame {

    /**
     * Creates new form PlayOffTitulo
     */
    public PlayOffTitulo() {
        initComponents();
    }
    
     public PlayOffTitulo(String cf1, String cf2, String cf3, String cf4, String cf5, String cf6, String cf7, String cf8 ){
        initComponents();
        cuartofinalista1.setText(cf1);
        cuartofinalista2.setText(cf2);
        cuartofinalista3.setText(cf3);
        cuartofinalista4.setText(cf4);
        cuartofinalista5.setText(cf5);
        cuartofinalista6.setText(cf6);
        cuartofinalista7.setText(cf7);
        cuartofinalista8.setText(cf8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuartofinalista1 = new javax.swing.JButton();
        cuartofinalista2 = new javax.swing.JButton();
        t1cuartofinalista1 = new javax.swing.JTextField();
        t1cuartofinalista2 = new javax.swing.JTextField();
        t2cuartofinalista1 = new javax.swing.JTextField();
        t2cuartofinalista2 = new javax.swing.JTextField();
        t3cuartofinalista1 = new javax.swing.JTextField();
        t3cuartofinalista2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cuartosfinal1 = new javax.swing.JButton();
        cuartosfinal3 = new javax.swing.JButton();
        cuartofinalista5 = new javax.swing.JButton();
        cuartofinalista6 = new javax.swing.JButton();
        t1cuartofinalista5 = new javax.swing.JTextField();
        t1cuartofinalista6 = new javax.swing.JTextField();
        t2cuartofinalista5 = new javax.swing.JTextField();
        t2cuartofinalista6 = new javax.swing.JTextField();
        t3cuartofinalista5 = new javax.swing.JTextField();
        t3cuartofinalista6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cuartosfinal4 = new javax.swing.JButton();
        cuartofinalista7 = new javax.swing.JButton();
        cuartofinalista8 = new javax.swing.JButton();
        t1cuartofinalista7 = new javax.swing.JTextField();
        t1cuartofinalista8 = new javax.swing.JTextField();
        t2cuartofinalista7 = new javax.swing.JTextField();
        t2cuartofinalista8 = new javax.swing.JTextField();
        t3cuartofinalista7 = new javax.swing.JTextField();
        t3cuartofinalista8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cuartosfinal2 = new javax.swing.JButton();
        cuartofinalista3 = new javax.swing.JButton();
        cuartofinalista4 = new javax.swing.JButton();
        t1cuartofinalista3 = new javax.swing.JTextField();
        t1cuartofinalista4 = new javax.swing.JTextField();
        t2cuartofinalista3 = new javax.swing.JTextField();
        t2cuartofinalista4 = new javax.swing.JTextField();
        t3cuartofinalista3 = new javax.swing.JTextField();
        t3cuartofinalista4 = new javax.swing.JTextField();
        t3semifinalista2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        semifinal1 = new javax.swing.JButton();
        semifinalista1 = new javax.swing.JButton();
        semifinalista2 = new javax.swing.JButton();
        t1semifinalista1 = new javax.swing.JTextField();
        t1semifinalista2 = new javax.swing.JTextField();
        t2semifinalista1 = new javax.swing.JTextField();
        t2semifinalista2 = new javax.swing.JTextField();
        t3semifinalista1 = new javax.swing.JTextField();
        t3semifinalista4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        semifinal2 = new javax.swing.JButton();
        semifinalista3 = new javax.swing.JButton();
        semifinalista4 = new javax.swing.JButton();
        t1semifinalista3 = new javax.swing.JTextField();
        t1semifinalista4 = new javax.swing.JTextField();
        t2semifinalista3 = new javax.swing.JTextField();
        t2semifinalista4 = new javax.swing.JTextField();
        t3semifinalista3 = new javax.swing.JTextField();
        finalista1 = new javax.swing.JButton();
        finalista2 = new javax.swing.JButton();
        t1finalista1 = new javax.swing.JTextField();
        t2finalista1 = new javax.swing.JTextField();
        t3finalista1 = new javax.swing.JTextField();
        t4finalista1 = new javax.swing.JTextField();
        t5finalista1 = new javax.swing.JTextField();
        t1finalista2 = new javax.swing.JTextField();
        t2finalista2 = new javax.swing.JTextField();
        t3finalista2 = new javax.swing.JTextField();
        t4finalista2 = new javax.swing.JTextField();
        t5finalista2 = new javax.swing.JTextField();
        final1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        winner = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        cuartofinalista1.setText("EL POZO MURCIA");

        cuartofinalista2.setText("LEVANTE UD");

        jLabel1.setText("CUARTOS DE FINAL");

        cuartosfinal1.setText("CALCULAR");
        cuartosfinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartosfinal1ActionPerformed(evt);
            }
        });

        cuartosfinal3.setText("CALCULAR");
        cuartosfinal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartosfinal3ActionPerformed(evt);
            }
        });

        cuartofinalista5.setText("MOVISTAR INTER");

        cuartofinalista6.setText("PALMA FUTSAL");

        jLabel3.setText("CUARTOS DE FINAL");

        jLabel4.setText("CUARTOS DE FINAL");

        cuartosfinal4.setText("CALCULAR");
        cuartosfinal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartosfinal4ActionPerformed(evt);
            }
        });

        cuartofinalista7.setText("JAEN FS");

        cuartofinalista8.setText("JIMBEE CARTAGENA");

        jLabel5.setText("CUARTOS DE FINAL");

        cuartosfinal2.setText("CALCULAR");
        cuartosfinal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartosfinal2ActionPerformed(evt);
            }
        });

        cuartofinalista3.setText("BARCELONA LASSA");

        cuartofinalista4.setText("OSASUNA MAGNA");

        jLabel6.setText("SEMIFINALES");

        semifinal1.setText("CALCULAR");
        semifinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semifinal1ActionPerformed(evt);
            }
        });

        jLabel7.setText("SEMIFINALES");

        semifinal2.setText("CALCULAR");
        semifinal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semifinal2ActionPerformed(evt);
            }
        });

        final1.setText("CALCULAR");
        final1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                final1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FINAL");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("WINNER");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PLAY OFFS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(semifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1semifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2semifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3semifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(semifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1semifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2semifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3semifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(semifinal1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(semifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1semifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2semifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3semifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(semifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1semifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2semifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3semifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(semifinal2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(winner, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t1finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t2finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t3finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t4finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t5finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t1finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t2finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t4finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t5finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(final1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1cuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2cuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3cuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cuartosfinal1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1cuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2cuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3cuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1cuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2cuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3cuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cuartosfinal2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 668, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t2cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cuartosfinal3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(t1cuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(t2cuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(t3cuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(t1cuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(t2cuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(t3cuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cuartosfinal4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t1cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t2cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3cuartofinalista5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t1cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t2cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3cuartofinalista6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(cuartosfinal3)))
                        .addGap(113, 113, 113)
                        .addComponent(jLabel7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t1semifinalista3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t2semifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3semifinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t1semifinalista4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(t2semifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t3semifinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(semifinal2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t1cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t2cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3cuartofinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t1cuartofinalista2)
                                        .addComponent(t2cuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3cuartofinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cuartosfinal1)
                                    .addComponent(jLabel8))
                                .addGap(41, 41, 41)))
                        .addGap(86, 86, 86)
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t1semifinalista1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t2semifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3semifinalista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t1semifinalista2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(t2semifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t3semifinalista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(semifinal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t2finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t4finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t5finalista1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(finalista1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t1finalista1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(t2finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t3finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t4finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t5finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(t1finalista2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(139, 139, 139)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t2cuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3cuartofinalista3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t1cuartofinalista3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(t1cuartofinalista4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(t2cuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t3cuartofinalista4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(cuartosfinal2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(final1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(winner))))
                        .addGap(155, 155, 155)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t1cuartofinalista7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t2cuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t3cuartofinalista7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t1cuartofinalista8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(t2cuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t3cuartofinalista8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(cuartosfinal4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(211, 211, 211))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuartosfinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartosfinal1ActionPerformed
        // TODO add your handling code here:
        try {
            int pg1 = 0;
            int pg2 = 0;
            int num1 = Integer.parseInt(t1cuartofinalista1.getText());
            int num2 = Integer.parseInt(t1cuartofinalista2.getText());
            if(num1 > num2){
                pg1++;
            }else if(num2 > num1){
                pg2++;
            }
            num1 = Integer.parseInt(t2cuartofinalista1.getText());
            num2 = Integer.parseInt(t2cuartofinalista2.getText());
            if(num1 > num2){
                pg1++;
                if(pg1 == 2){
                     semifinalista1.setText(cuartofinalista1.getText());
                }else{
                    num1 = Integer.parseInt(t3cuartofinalista1.getText());
                    num2 = Integer.parseInt(t3cuartofinalista2.getText());
                    if(num1 > num2){
                        semifinalista1.setText(cuartofinalista1.getText());
                    }else if(num2 > num1){
                        semifinalista1.setText(cuartofinalista2.getText());
                    }       
                }
            }else if(num2 > num1){
                pg2++;
                if(pg2 == 2){
                    semifinalista1.setText(cuartofinalista2.getText());
                }else{
                    num1 = Integer.parseInt(t3cuartofinalista1.getText());
                    num2 = Integer.parseInt(t3cuartofinalista2.getText());
                    if(num1 > num2){
                        semifinalista1.setText(cuartofinalista1.getText());
                    }else if(num2 > num1){
                        semifinalista1.setText(cuartofinalista2.getText());
                    }       
                }
            }
            
        }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(this, "Formato invalido");

        }
    }//GEN-LAST:event_cuartosfinal1ActionPerformed

    private void cuartosfinal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartosfinal2ActionPerformed
        // TODO add your handling code here:
         try {
            int pg1 = 0;
            int pg2 = 0;
            int num1 = Integer.parseInt(t1cuartofinalista3.getText());
            int num2 = Integer.parseInt(t1cuartofinalista4.getText());
            if(num1 > num2){
                pg1++;
            }else if(num2 > num1){
                pg2++;
            }
            num1 = Integer.parseInt(t2cuartofinalista3.getText());
            num2 = Integer.parseInt(t2cuartofinalista4.getText());
            if(num1 > num2){
                pg1++;
                if(pg1 == 2){
                     semifinalista2.setText(cuartofinalista3.getText());
                }else{
                    num1 = Integer.parseInt(t3cuartofinalista3.getText());
                    num2 = Integer.parseInt(t3cuartofinalista4.getText());
                    if(num1 > num2){
                        semifinalista2.setText(cuartofinalista3.getText());
                    }else if(num2 > num1){
                        semifinalista2.setText(cuartofinalista4.getText());
                    }       
                }
            }else if(num2 > num1){
                pg2++;
                if(pg2 == 2){
                    semifinalista2.setText(cuartofinalista4.getText());
                }else{
                    num1 = Integer.parseInt(t3cuartofinalista3.getText());
                    num2 = Integer.parseInt(t3cuartofinalista4.getText());
                    if(num1 > num2){
                        semifinalista2.setText(cuartofinalista3.getText());
                    }else if(num2 > num1){
                        semifinalista2.setText(cuartofinalista4.getText());
                    }       
                }
            }
            
        }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(this, "Formato invalido");

        }
        
    }//GEN-LAST:event_cuartosfinal2ActionPerformed

    private void cuartosfinal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartosfinal3ActionPerformed
        // TODO add your handling code here:
         try {
            int pg1 = 0;
            int pg2 = 0;
            int num1 = Integer.parseInt(t1cuartofinalista5.getText());
            int num2 = Integer.parseInt(t1cuartofinalista6.getText());
            if(num1 > num2){
                pg1++;
            }else if(num2 > num1){
                pg2++;
            }
            num1 = Integer.parseInt(t2cuartofinalista5.getText());
            num2 = Integer.parseInt(t2cuartofinalista6.getText());
            if(num1 > num2){
                pg1++;
                if(pg1 == 2){
                     semifinalista3.setText(cuartofinalista5.getText());
                }else{
                    num1 = Integer.parseInt(t3cuartofinalista5.getText());
                    num2 = Integer.parseInt(t3cuartofinalista6.getText());
                    if(num1 > num2){
                        semifinalista3.setText(cuartofinalista5.getText());
                    }else if(num2 > num1){
                        semifinalista3.setText(cuartofinalista6.getText());
                    }       
                }
            }else if(num2 > num1){
                pg2++;
                if(pg2 == 2){
                    semifinalista3.setText(cuartofinalista6.getText());
                }else{
                    num1 = Integer.parseInt(t3cuartofinalista5.getText());
                    num2 = Integer.parseInt(t3cuartofinalista6.getText());
                    if(num1 > num2){
                        semifinalista3.setText(cuartofinalista5.getText());
                    }else if(num2 > num1){
                        semifinalista3.setText(cuartofinalista6.getText());
                    }       
                }
            }
            
        }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(this, "Formato invalido");

        }
    }//GEN-LAST:event_cuartosfinal3ActionPerformed

    private void cuartosfinal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartosfinal4ActionPerformed
        // TODO add your handling code here:
         try {
            int pg1 = 0;
            int pg2 = 0;
            int num1 = Integer.parseInt(t1cuartofinalista7.getText());
            int num2 = Integer.parseInt(t1cuartofinalista8.getText());
            if(num1 > num2){
                pg1++;
            }else if(num2 > num1){
                pg2++;
            }
            num1 = Integer.parseInt(t2cuartofinalista7.getText());
            num2 = Integer.parseInt(t2cuartofinalista8.getText());
            if(num1 > num2){
                pg1++;
                if(pg1 == 2){
                     semifinalista4.setText(cuartofinalista7.getText());
                }else{
                    num1 = Integer.parseInt(t3cuartofinalista7.getText());
                    num2 = Integer.parseInt(t3cuartofinalista8.getText());
                    if(num1 > num2){
                        semifinalista4.setText(cuartofinalista7.getText());
                    }else if(num2 > num1){
                        semifinalista4.setText(cuartofinalista8.getText());
                    }       
                }
            }else if(num2 > num1){
                pg2++;
                if(pg2 == 2){
                    semifinalista4.setText(cuartofinalista8.getText());
                }else{
                    num1 = Integer.parseInt(t3cuartofinalista7.getText());
                    num2 = Integer.parseInt(t3cuartofinalista8.getText());
                    if(num1 > num2){
                        semifinalista4.setText(cuartofinalista7.getText());
                    }else if(num2 > num1){
                        semifinalista4.setText(cuartofinalista8.getText());
                    }       
                }
            }
            
        }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(this, "Formato invalido");

        }
    }//GEN-LAST:event_cuartosfinal4ActionPerformed

    private void semifinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semifinal1ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        if("".equals(semifinalista1.getText()) || "".equals(semifinalista2.getText())){
            JOptionPane.showMessageDialog(this, "Falta un partido por disputarse");
            t1semifinalista1.setText("");
            t1semifinalista2.setText("");
            t2semifinalista1.setText("");
            t2semifinalista2.setText("");
            t3semifinalista1.setText("");
            t3semifinalista2.setText("");
        }else{
            try {
                int pg1 = 0;
                int pg2 = 0;
                int num1 = Integer.parseInt(t1semifinalista1.getText());
                int num2 = Integer.parseInt(t1semifinalista2.getText());
                if(num1 > num2){
                    pg1++;
                }else if(num2 > num1){
                    pg2++;
                }
                num1 = Integer.parseInt(t2semifinalista1.getText());
                num2 = Integer.parseInt(t2semifinalista2.getText());
                if(num1 > num2){
                    pg1++;
                    if(pg1 == 2){
                         finalista1.setText(semifinalista1.getText());
                    }else{
                        num1 = Integer.parseInt(t3semifinalista1.getText());
                        num2 = Integer.parseInt(t3semifinalista2.getText());
                        if(num1 > num2){
                            finalista1.setText(semifinalista1.getText());
                        }else if(num2 > num1){
                            finalista1.setText(semifinalista2.getText());
                        }       
                    }
                }else if(num2 > num1){
                    pg2++;
                    if(pg2 == 2){
                        finalista1.setText(semifinalista2.getText());
                    }else{
                        num1 = Integer.parseInt(t3semifinalista1.getText());
                        num2 = Integer.parseInt(t3semifinalista2.getText());
                        if(num1 > num2){
                            finalista1.setText(semifinalista1.getText());
                        }else if(num2 > num1){
                            finalista1.setText(semifinalista2.getText());
                        }       
                    }
                }
            
            }catch(NumberFormatException e){
                     JOptionPane.showMessageDialog(this, "Formato invalido");

            }    
        }
        
    }//GEN-LAST:event_semifinal1ActionPerformed

    private void semifinal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semifinal2ActionPerformed
        // TODO add your handling code here:
         if("".equals(semifinalista3.getText()) || "".equals(semifinalista4.getText())){
            JOptionPane.showMessageDialog(this, "Falta un partido por disputarse");
            t1semifinalista3.setText("");
            t1semifinalista4.setText("");
            t2semifinalista3.setText("");
            t2semifinalista4.setText("");
            t3semifinalista3.setText("");
            t3semifinalista4.setText("");
        }else{
            try {
                int pg1 = 0;
                int pg2 = 0;
                int num1 = Integer.parseInt(t1semifinalista3.getText());
                int num2 = Integer.parseInt(t1semifinalista4.getText());
                if(num1 > num2){
                    pg1++;
                }else if(num2 > num1){
                    pg2++;
                }
                num1 = Integer.parseInt(t2semifinalista3.getText());
                num2 = Integer.parseInt(t2semifinalista4.getText());
                if(num1 > num2){
                    pg1++;
                    if(pg1 == 2){
                         finalista2.setText(semifinalista3.getText());
                    }else{
                        num1 = Integer.parseInt(t3semifinalista3.getText());
                        num2 = Integer.parseInt(t3semifinalista4.getText());
                        if(num1 > num2){
                            finalista2.setText(semifinalista3.getText());
                        }else if(num2 > num1){
                            finalista2.setText(semifinalista4.getText());
                        }       
                    }
                }else if(num2 > num1){
                    pg2++;
                    if(pg2 == 2){
                        finalista2.setText(semifinalista4.getText());
                    }else{
                        num1 = Integer.parseInt(t3semifinalista3.getText());
                        num2 = Integer.parseInt(t3semifinalista4.getText());
                        if(num1 > num2){
                            finalista2.setText(semifinalista3.getText());
                        }else if(num2 > num1){
                            finalista2.setText(semifinalista4.getText());
                        }       
                    }
                }
            
            }catch(NumberFormatException e){
                     JOptionPane.showMessageDialog(this, "Formato invalido");

            }    
        }
        
        
    }//GEN-LAST:event_semifinal2ActionPerformed

    private void final1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_final1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
         if("".equals(finalista1.getText()) || "".equals(finalista2.getText())){
            JOptionPane.showMessageDialog(this, "Falta un partido por disputarse");
            t1finalista1.setText("");
            t1finalista2.setText("");
            t2finalista1.setText("");
            t2finalista2.setText("");
            t3finalista1.setText("");
            t3finalista2.setText("");
            t4finalista1.setText("");
            t4finalista2.setText("");
            t5finalista1.setText("");
            t5finalista2.setText("");
        }else{
            try {
                int pg1 = 0;
                int pg2 = 0;
                int num1 = Integer.parseInt(t1finalista1.getText());
                int num2 = Integer.parseInt(t1finalista2.getText());
                if(num1 > num2){
                    pg1++;
                }else if(num2 > num1){
                    pg2++;
                }
                num1 = Integer.parseInt(t2finalista1.getText());
                num2 = Integer.parseInt(t2finalista2.getText());
                if(num1 > num2){
                    pg1++;
                }else if(num2 > num1){
                    pg2++;
                }
                num1 = Integer.parseInt(t3finalista1.getText());
                num2 = Integer.parseInt(t3finalista2.getText());
                if(num1 > num2){
                    pg1++;
                    if(pg1 == 3){
                         winner.setText(finalista1.getText());
                    }else{
                        num1 = Integer.parseInt(t4finalista1.getText());
                        num2 = Integer.parseInt(t4finalista2.getText());
                        if(num1 > num2){
                            pg1++;
                            if(pg1 == 3){
                                winner.setText(finalista1.getText());
                            }else{
                                 num1 = Integer.parseInt(t5finalista1.getText());
                                 num2 = Integer.parseInt(t5finalista2.getText());
                                 if(num1 > num2){
                                    winner.setText(finalista1.getText());
                                }else if(num2 > num1){
                                    winner.setText(finalista2.getText());
                                }        
                            }
                        }else if(num2 > num1){
                            pg2++;
                            if(pg2 == 3){
                                winner.setText(finalista2.getText());
                            }else{
                                 num1 = Integer.parseInt(t5finalista1.getText());
                                 num2 = Integer.parseInt(t5finalista2.getText());
                                 if(num1 > num2){
                                    winner.setText(finalista1.getText());
                                }else if(num2 > num1){
                                    winner.setText(finalista2.getText());
                                }        
                            }
                        }       
                    }
                }else if(num2 > num1){
                    pg2++;
                    if(pg2 == 3){
                        winner.setText(finalista2.getText());
                    }else{
                        num1 = Integer.parseInt(t4finalista1.getText());
                        num2 = Integer.parseInt(t4finalista2.getText());
                        if(num1 > num2){
                            pg1++;
                            if(pg1 == 3){
                                winner.setText(finalista1.getText());
                            }else{
                                 num1 = Integer.parseInt(t5finalista1.getText());
                                 num2 = Integer.parseInt(t5finalista2.getText());
                                 if(num1 > num2){
                                    winner.setText(finalista1.getText());
                                }else if(num2 > num1){
                                    winner.setText(finalista2.getText());
                                }        
                            }
                        }else if(num2 > num1){
                            pg2++;
                            if(pg2 == 3){
                                winner.setText(finalista2.getText());
                            }else{
                                 num1 = Integer.parseInt(t5finalista1.getText());
                                 num2 = Integer.parseInt(t5finalista2.getText());
                                 if(num1 > num2){
                                    winner.setText(finalista1.getText());
                                }else if(num2 > num1){
                                    winner.setText(finalista2.getText());
                                }        
                            }
                        }      
                    }
                }
            
            }catch(NumberFormatException e){
                     JOptionPane.showMessageDialog(this, "Formato invalido");

            }    
        }
        
    }//GEN-LAST:event_final1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayOffTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayOffTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayOffTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayOffTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayOffTitulo().setVisible(true);
            }
        });
    }
    
    public String winner(){
        while("".equals(winner.getText())){
            
        }
        return winner.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cuartofinalista1;
    private javax.swing.JButton cuartofinalista2;
    private javax.swing.JButton cuartofinalista3;
    private javax.swing.JButton cuartofinalista4;
    private javax.swing.JButton cuartofinalista5;
    private javax.swing.JButton cuartofinalista6;
    private javax.swing.JButton cuartofinalista7;
    private javax.swing.JButton cuartofinalista8;
    private javax.swing.JButton cuartosfinal1;
    private javax.swing.JButton cuartosfinal2;
    private javax.swing.JButton cuartosfinal3;
    private javax.swing.JButton cuartosfinal4;
    private javax.swing.JButton final1;
    private javax.swing.JButton finalista1;
    private javax.swing.JButton finalista2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton semifinal1;
    private javax.swing.JButton semifinal2;
    private javax.swing.JButton semifinalista1;
    private javax.swing.JButton semifinalista2;
    private javax.swing.JButton semifinalista3;
    private javax.swing.JButton semifinalista4;
    private javax.swing.JTextField t1cuartofinalista1;
    private javax.swing.JTextField t1cuartofinalista2;
    private javax.swing.JTextField t1cuartofinalista3;
    private javax.swing.JTextField t1cuartofinalista4;
    private javax.swing.JTextField t1cuartofinalista5;
    private javax.swing.JTextField t1cuartofinalista6;
    private javax.swing.JTextField t1cuartofinalista7;
    private javax.swing.JTextField t1cuartofinalista8;
    private javax.swing.JTextField t1finalista1;
    private javax.swing.JTextField t1finalista2;
    private javax.swing.JTextField t1semifinalista1;
    private javax.swing.JTextField t1semifinalista2;
    private javax.swing.JTextField t1semifinalista3;
    private javax.swing.JTextField t1semifinalista4;
    private javax.swing.JTextField t2cuartofinalista1;
    private javax.swing.JTextField t2cuartofinalista2;
    private javax.swing.JTextField t2cuartofinalista3;
    private javax.swing.JTextField t2cuartofinalista4;
    private javax.swing.JTextField t2cuartofinalista5;
    private javax.swing.JTextField t2cuartofinalista6;
    private javax.swing.JTextField t2cuartofinalista7;
    private javax.swing.JTextField t2cuartofinalista8;
    private javax.swing.JTextField t2finalista1;
    private javax.swing.JTextField t2finalista2;
    private javax.swing.JTextField t2semifinalista1;
    private javax.swing.JTextField t2semifinalista2;
    private javax.swing.JTextField t2semifinalista3;
    private javax.swing.JTextField t2semifinalista4;
    private javax.swing.JTextField t3cuartofinalista1;
    private javax.swing.JTextField t3cuartofinalista2;
    private javax.swing.JTextField t3cuartofinalista3;
    private javax.swing.JTextField t3cuartofinalista4;
    private javax.swing.JTextField t3cuartofinalista5;
    private javax.swing.JTextField t3cuartofinalista6;
    private javax.swing.JTextField t3cuartofinalista7;
    private javax.swing.JTextField t3cuartofinalista8;
    private javax.swing.JTextField t3finalista1;
    private javax.swing.JTextField t3finalista2;
    private javax.swing.JTextField t3semifinalista1;
    private javax.swing.JTextField t3semifinalista2;
    private javax.swing.JTextField t3semifinalista3;
    private javax.swing.JTextField t3semifinalista4;
    private javax.swing.JTextField t4finalista1;
    private javax.swing.JTextField t4finalista2;
    private javax.swing.JTextField t5finalista1;
    private javax.swing.JTextField t5finalista2;
    private javax.swing.JTextField winner;
    // End of variables declaration//GEN-END:variables
}
